/*
	Author: Aaron Clark - EpochMod.com

    Contributors:

	Description:
	BASE Epoch Server Events !!!DO NOT EDIT THIS FILE!!! Copy the epoch_server_debris_event to make new ones.

    Licence:
    Arma Public License Share Alike (APL-SA) - https://www.bistudio.com/community/licenses/arma-public-license-share-alike

    Github:
    https://github.com/EpochModTeam/Epoch/tree/release/Sources/epoch_server_settngs/config.cpp
*/

#define _ARMA_

class CfgPatches {
	class A3_server_events {
		requiredVersion = 0.1;
		requiredAddons[] = {};
        #include "build.hpp"
	};
};

// import settings
class CfgEpochServerEvents
{
    /* EXAMPLES ONLY !!! DO NOT EDIT THIS FILE make a copy of the Dynamic Debris Event !!!
    class ContainerSpawner {
        delay = 1200; // delay in seconds between executions <SCALAR>,
        script = "\epoch_server_events\EpochEvents\ContainerSpawner.sqf"; // script: name or full path if usePrefix is set to 0
        runOnStart = 0; // runOnStart: 1 = run script at startup, 0 normal delay
        usePrefix = 0; // usePrefix: 1 = use pre/postfix path (inside epoch settings pbo EpochEvents folder) 0 = use full file path
        runNumTimes = -1; // runNumTimes: -1 = no limit, 0 = disabled, 1+ = number of times to execute before removing event.
        input[] = {}; // array input to execVM at time of run and accessed with _this inside of script.
    };
    class AirDrop {
        delay = 2700; // delay in seconds between executions <SCALAR>,
        script = "AirDrop"; // script: name or full path if usePrefix is set to 0
        runOnStart = 0; // runOnStart: 1 = run script at startup, 0 normal delay
        usePrefix = 2; // usePrefix: 1 = use pre/postfix path (inside epoch settings pbo EpochEvents folder) 0 = use full file path
        runNumTimes = -1; // runNumTimes: -1 = no limit, 0 = disabled, 1+ = number of times to execute before removing event.
        input[] = {}; // array input to execVM at time of run and accessed with _this inside of script.
    };
    */
};
