// convert array if items to loot config format

_items = ["U_JeansPatched1_uniform",
"U_JeansPatched2_uniform",
"U_JeansPatched3_uniform",
"U_JeansPatched4_uniform",
"U_JeansPatched5_uniform",
"U_JeansPatched6_uniform",
"U_JeansPatched7_uniform",
"U_JeansPatched8_uniform",
"U_JeansPatched9_uniform",
"U_JeansPatched10_uniform",
"U_JeansPatched11_uniform",
"U_JeansPatched12_uniform",
"U_JeansPatched13_uniform",
"U_JeansPatched14_uniform",
"U_JeansPatched15_uniform",
"U_JeansPatched16_uniform",
"U_JeansPatched17_uniform",
"U_JeansPatched18_uniform",
"U_JeansPatched19_uniform",
"U_JeansPatched20_uniform",
"U_JeansPatched21_uniform",
"U_JeansBlkBrn1_uniform",
"U_JeansBlkBrn2_uniform",
"U_JeansBlkBrn3_uniform",
"U_JeansBlkBrn4_uniform",
"U_JeansBlkBrn5_uniform",
"U_JeansBlkBrn6_uniform",
"U_JeansBlkBrn7_uniform",
"U_JeansBlkBrn8_uniform",
"U_JeansBlkBrn9_uniform",
"U_JeansBlkBrn10_uniform",
"U_JeansBlkBrn11_uniform",
"U_JeansBlkBrn12_uniform",
"U_JeansBlkBrn13_uniform",
"U_JeansBlkBrn14_uniform",
"U_JeansBlkBrn15_uniform",
"U_JeansBlkBrn16_uniform",
"U_JeansBlkBrn17_uniform",
"U_JeansBlkBrn18_uniform",
"U_JeansBlkBrn19_uniform",
"U_JeansBlkBrn20_uniform",
"U_JeansBlkBrn21_uniform",
"U_JeansArBrn1_uniform",
"U_JeansArBrn2_uniform",
"U_JeansArBrn3_uniform",
"U_JeansArBrn4_uniform",
"U_JeansArBrn5_uniform",
"U_JeansArBrn6_uniform",
"U_JeansArBrn7_uniform",
"U_JeansArBrn8_uniform",
"U_JeansArBrn9_uniform",
"U_JeansArBrn10_uniform",
"U_JeansArBrn11_uniform",
"U_JeansArBrn12_uniform",
"U_JeansArBrn13_uniform",
"U_JeansArBrn14_uniform",
"U_JeansArBrn15_uniform",
"U_JeansArBrn16_uniform",
"U_JeansArBrn17_uniform",
"U_JeansArBrn18_uniform",
"U_JeansArBrn19_uniform",
"U_JeansArBrn20_uniform",
"U_JeansArBrn21_uniform",
"U_JeansBlack1_uniform",
"U_JeansBlack2_uniform",
"U_JeansBlack3_uniform",
"U_JeansBlack4_uniform",
"U_JeansBlack5_uniform",
"U_JeansBlack6_uniform",
"U_JeansBlack7_uniform",
"U_JeansBlack8_uniform",
"U_JeansBlack9_uniform",
"U_JeansBlack10_uniform",
"U_JeansBlack11_uniform",
"U_JeansBlack12_uniform",
"U_JeansBlack13_uniform",
"U_JeansBlack14_uniform",
"U_JeansBlack15_uniform",
"U_JeansBlack16_uniform",
"U_JeansBlack17_uniform",
"U_JeansBlack18_uniform",
"U_JeansBlack19_uniform",
"U_JeansBlack20_uniform",
"U_JeansBlack21_uniform"];

_configStr = "";
{
	_configStr = _configStr + format['
{ { "%1", "item" }, 1 },',_x];
} forEach _items;

copyToClipboard _configStr;
