#define info call _sendInfo
#define warning call _sendWarning
#define critical call _sendCritical

#define	ST_SIZE18 "size='1.8'"
#define	ST_SIZE2 "size='2'"
#define	ST_SKYBLUE "color='#00D0DF'"
#define	ST_GREEN "color='#A5FD6B'"
#define	ST_ORANGE "color='#FEA834'"
#define	ST_RED "color='#ff0000'"
#define	ST_WHITE "color='#FFFFFF'"
#define	ST_TAHOMAB "font='TahomaB'"
#define	ST_PURISTAMEDIUM "font='PuristaMedium'"
#define	ST_SHADOW1 "shadow='1' shadowColor='#000000'"
#define	ST_SHADOW2 "shadow='2'"
#define ST_INFO "<img image='x\addons\rmx_init\data\info.paa'/>"
#define ST_WARNING "<img image='x\addons\rmx_init\data\warning.paa'/>"
#define ST_CRITICAL "<img image='x\addons\rmx_init\data\critical.paa'/>"